id: P49947FE4
initial_creation_type: input
source_metadata:
  title: Confession Series
  language: zh
  description: 'Lotsawa House presents the following texts related to the practice
    of confession (bshags pa):'
  volume:
    0ee565e92d24496e94b087e1b7480249:
      title: Daily Confession (from the Vajrapañjara Tantra)
      parent: Canonical Works
    daea497941d04054aecfe634db571387:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Canonical Works
    848efc84497347b0910ae0d1973c6481:
      title: The Lament of Rudra
      parent: Practices
    eb737b25f7fa4a8b9d4f0ba4c62e636f:
      title: The Noble Sūtra of the Teaching on the Four Factors
      parent: Canonical Works
    94520a4f19694e2c83df680aa626572e:
      title: The Ultimate Inexpressible Confession (Yeshe Kuchokma)
      parent: Canonical Works
    f5abb9663a3140c0947a58f11707a65f:
      title: Verses of Confession 'Düsum Deshekma'
      parent: Canonical Works
    1f5ec0914d0d43b8a7918263318bdb80:
      title: Guide to the Practice of Narak Kong Shak
      parent: Commentaries
    b6c84876f2f2476782f91e0a249fe80a:
      title: A Topical Outline of the General Confession Spoken by the Five Great
        Sages
      parent: Outlines
    832a9ad5cc084c05b30e6311a3840537:
      title: Root Downfalls of the Vajra Vehicle
      parent: Practices
    a94a5f7d16d44dc5b013cea9ff0f217a:
      title: The Inexpressible, Ultimate Confession (Yeshe Kuchokma)
      parent: Practices
    753f444b8ee64912b3341500a09f8725:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Practices
    be56aa6e3c9440c8858a690ca5d3cc77:
      title: 'Emptying the Hells from their Very Depths: The Sovereign Practice for
        the Confession of all Impairments and Breakages of Vows and all Negative Actions
        and Obscurations'
      parent: Practices
    908dfaa6c4794a69a0a84328e880b986:
      title: A Practice of Fulfilment and Confession to an Ocean of Oath-bound Protectors
      parent: Practices
    4d253fe4cc9642b2bad96e13b6a95411:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Practices
    f394cd2372d5488ba847200a6853f1a0:
      title: A Discourse on the Confession of Harmful Deeds Spoken by Yama Dharmarāja
        to Karma Chakme
      parent: Practices
    2969b427736843eba886abdee8766cb5:
      title: Brief Confession to the Earth Lords
      parent: Practices
    b84148f9aa774bba93c8f480c261ea69:
      title: A Method of Confessing and Pledging through the Four Powers
      parent: Practices
    27736722919249cf92882499ceda31f5:
      title: Rays of Moonlight to Dispel the Darkness of Misdeeds
      parent: Practices
    f8a6b3ea4e0f463aab20b9f8f4bb07a7:
      title: Method of Confession based on the Four Powers
      parent: Practices
    5ca1575458034d20b35b11335dcc7d93:
      title: The Sovereign of Confessions for all Impairments and Breakages, Extracted
        from the Rampant Elephant Tantra
      parent: Practices
    987eaafa79a14fc3b6c13ab0d398af60:
      title: A Prayer to Recognize My Own Faults and Keep in Mind the Objects of Refuge
      parent: Prayer
created_at: '2022-03-01T03:17:51.741401'
last_modified_at: '2022-03-01T03:17:51.741404'
